# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: News
    url: '#news'
    weight: 15
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Education
    url: '#education'
    weight: 25
  - name: Awards
    url: '#awards'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 35
  - name: Contact
    url: '#contact'
    weight: 40
  - name: CV
    url: uploads/Yuhao_Wu_CV.pdf
    weight: 45
